"""add durable queued messages

Revision ID: 6e21b3c2cfcd
Revises: f8d83c52cf7f
Create Date: 2026-04-14 14:23:13.665768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e21b3c2cfcd'
down_revision: Union[str, Sequence[str], None] = 'f8d83c52cf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queued_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queued_messages_topic'), ['topic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queued_messages_topic'))

    op.drop_table('queued_messages')
    # ### end Alembic commands ###
